### PR TITLE
feat(html): added the option to set the HTML document title

### PR DESCRIPTION
**Pull request by gjdonkers**
Added the option to set the HTML Title. When generating the PDF the variable title is now set to be used in the headerTemplate and footerTemplate.

### CODE REVIEW

**Comment by simonhaenisch** [comment]
Thanks for the PR, looks good!

Can you just give an example for how to access the title from the header/footer templates?

**Comment by simonhaenisch** [comment]
Actually, more interesting: would it make sense to default this to the file name, or is that already covered by the `url` variable?

**Comment by gjdonkers** [comment]
The `url` variable would be something like `http://localhost:57653/ReadMe.md#`, so this would not be usable. The first header in the Markdown could be something, but I don't know how to fix that.

**Comment by simonhaenisch** [comment]
Ok yeah using the first `h1` would definitely make sense but it's not super straight-forward. Could be solved by injecting a script into the document that does sth like

```js
const h1 = document.querySelector('h1');

if (h1) {
  document.title = h1.textContent;
}
```

**Review by simonhaenisch — APPROVED** [review]

**Comment by gjdonkers** [comment]
I completely agree with you on that. How is your release pipeline plannend? In other words when will this be available in the npm package?

**Comment by gjdonkers** [comment]
I just found out you've Actions defined, but the one on macOS is failed. I don't know why that happend, do you know?

**Comment by simonhaenisch** [comment]
Hm looks like it was just a puppeteer error, the tests passed on all other matrix runs. Sadly it's a bit flakey sometimes, i think it's a puppeteer issue.

Regarding releasing, will see that I can get it done later or tmrw morning.

**Comment by simonhaenisch** [comment]
Just released 4.1.0 🚀

**Pull request merged**
