### PR TITLE
Add option to generate html instead of pdf

### LINKED ISSUE #30: Add a flag to output html instead of (or besides) pdf.
In my case, I am writing my CV in Markdown and it'd be helpful to have both pdf and html versions to send pdf via email and have an html version on my website.

### PR DESCRIPTION
**Pull request by kleyu**
Using the `as_html` flag it is possible now to output HTML file instead of straight PDF conversion.

Thank you for providing guidance in #30 and awesome work on the tool!

Closes #30.

### CODE REVIEW

**Comment by simonhaenisch** [comment]
Thanks so much for the PR, I'll probably look into getting it merged and do a release tomorrow (:

**Comment by kleyu** [comment]
> 
> 
> Thanks so much for the PR, I'll probably look into getting it merged and do a release tomorrow (:
> 
> Also need to look into why CircleCI isn't running 🤔 (actually just found out that I just needed to enable it for forked PRs).

Great, If you need some help with the tool or have some plans for the future, let me know as I'd be happy to help.

**Comment by simonhaenisch** [comment]
Sry this has been taking a bit longer. I've been working through it and you missed a few things; a couple linter errors, the tests are failing, you forgot to add the cli flag to the help, you only modified `cli.js` but not `index.js`... nothing big.

However you introduced one change that I don't agree with: you are directly injecting the stylesheets and CSS into the html string, which is already done using Puppeteer's `page.addStyleTag()` function.

I'm not 100% sure how to go about this in general tbh. At the moment I see three solutions:

1. Inline all the CSS directly into the document (remote styles could be fetched); this would make the output most portable, but it sounds quite complex, and I also don't think it's in the scope of this package.

2. Don't generate a full HTML document including `<head/>` and `<body/>`, but only return the actual content that is generated from the markdown converter; this makes a lot of sense to me as that is the part that you would want to e. g. use as the content in a web page template (assuming that loading styles and stuff is handled by your website framework).

3. Use Puppeteer's `page.content()` to retrieve the HTML, which returns it in the same way as it would be used to render the page for the PDF generation.

For now my preferred solution is number 3 as this supports the most features, but I'd like to have your opinion as well. How are you intending to use this?

**Comment by simonhaenisch** [comment]
Actually just implemented solution 3 and gonna merge this now... if it turns out that's not a suitable solution, we can change it up. Want to do a major release soon anyway.

**Comment by kleyu** [comment]
@simonhaenisch Damn, I was working on fixing these in another commit. Unfortunately missed the tests, my bad. I believe it was missing from the readme :(

As for the HTML-pupeteer thingy, I'll get back to you and investigate in upcoming week.

**Comment by simonhaenisch** [comment]
@kleyu all good, no worries. Thanks a lot for the PR ❤️ Really appreciate the help (:

**Pull request merged**
